name: Reusable CD

on:
  workflow_call:
    inputs:
      artifact_run_id: { required: true, type: string }
      commit_sha: { required: true, type: string }
      branch: { required: true, type: string }
      version: { required: true, type: string }

permissions:
  actions: read
  contents: read

jobs:
  deploy-dev:
    if: inputs.branch == 'develop'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      artifact_run_id: ${{ inputs.artifact_run_id }}
      commit_sha: ${{ inputs.commit_sha }}
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
      cancel_in_progress: true
    secrets: inherit

  deploy-qa:
    if: inputs.branch == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: qa
      artifact_run_id: ${{ inputs.artifact_run_id }}
      commit_sha: ${{ inputs.commit_sha }}
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
      validate_qa: true
    secrets: inherit
